/**
 * The package's public face: the schema, and the row aliases the API reads it through.
 *
 * Two files, one package (ID67). `schema.ts` is the product's own tables, written
 * here. `auth-schema.ts` is the authentication library's — `user`, `session`,
 * `account`, `verification` — and is GENERATED by `auth generate` from the API's
 * `lib/auth` configuration, committed unmodified and never edited by hand (ID56): a
 * change wanted there is configured in the library and the file is regenerated. A
 * caller of this package sees both as one schema and cannot tell which file a table
 * came from, which is the point.
 *
 * There are no aliases yet because there are no tables of our own yet (SL10). When the
 * first one lands, its `typeof <table>.$inferSelect` and `.$inferInsert` are named here
 * rather than in each caller, so a row shape has one name in the repository.
 */
export * from "./auth-schema";
export * from "./schema";
