/**
 * The package's public face: the schema, and the row aliases the API reads it through.
 *
 * Two files, one package (ID67). `schema.ts` is the product's own tables, written
 * here. `auth-schema.ts` is the authentication library's — `user`, `session`,
 * `account`, `verification` — and is GENERATED by `auth generate` from the API's
 * `lib/auth` configuration, committed unmodified and never edited by hand (ID56): a
 * change wanted there is configured in the library and the file is regenerated. A
 * caller of this package sees both as one schema and cannot tell which file a table
 * came from, which is the point.
 *
 * **The row aliases are the package's, not each caller's** (the person's own comment:
 * *"For infered types, can we expose them from the db package, define alias there to be
 * reused"*). Every table of our own names its `$inferSelect` and, where a caller writes
 * rows, its `$inferInsert`, beside the table in `schema.ts` — `Document`, `NewDocument`,
 * `ProfileItem`, `Question`, `Rule` and the rest. A row shape therefore has one name in
 * the repository, and `typeof <table>.$inferSelect` written anywhere outside this
 * package is a name that was not reused.
 */
export * from "./auth-schema";
export * from "./schema";
